house_log/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [

    # Index (Home) Page
    path('', views.Index, name=""),

    # Login Page
    path('login', views.MyLogin, name='mylogin'),

    # Register
    path('register', views.Register, name='register'),


    # User Homepage
    path('homepage', views.UserHome, name='user-home'),

    # Logout
    path('logout', views.Logout, name='user-logout'),

    # User Profile
    path('user-profile', views.View_Profile, name='user-profile'),

    # Update Profile
    path('update-profile', views.Update_Profile, name='update-profile'),


    # Add house
    path('add-house', views.Add_House, name='add-house'),

    # View Houses
    path('view-houses', views.View_Houses, name='view-houses'),

    # Drill in on a house
    path('house/<str:pk>/', views.House_View, name='read-house'),

    # Update a house
    path('update-house/<str:pk>/', views.Update_House, name='update-house'),

    # Update status for a house
    path('update-status/<str:pk>/', views.UpdateStatus, name='update-status'),

    # Update notes for a house
    path('update-notes/<str:pk>', views.UpdateNotes, name='update-notes'),

    # Compare two houses
    # click compare houses -> form -> redirect 

    path('compare/', views.Comparator, name='compare-houses'),
    path('compare-houses/', views.Display_Comparison, name='display_comparison'),

    path('test/comparison', views.TestCompare, name="test-compare"),

    # Archive a house


    # Calculate commutes
    path('update-commutes/<str:pk>/', views.Update_Commutes, name='update-commutes'),

    # Update Lat/Long for all houses
    path('updatelatlong', views.UpdateLatLong, name='update-lat-long'), # you left off here. 
    # make a view, apply the service (possibly create a service)
    
    ]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

househunt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('house_log.urls'))
]

house_log/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.auth.models import User  # default User model from Django

# Create your models here.

class House(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return str(self.pk) + " | " + str(self.address)

    # = = = = = = Status = = = = = = #
    # ============================== #
    
    date_available = models.DateField(blank=True, null=True)

    next_steps = models.CharField(max_length=1000, blank=True, null=True) # next steps/last contact/resolution

    applied_status = models.BooleanField(blank=True, null=True)

    archive = models.BooleanField(default=False)

    # = = = House Information = = = #
    # ============================= #

    address = models.CharField(max_length=100)

    web_address = models.CharField(max_length=1000)

    # Type of home
    HOUSE=1
    SPLIT_HOUSE=2
    APARTMENT=3
    HOME_CHOICES = (
        (HOUSE, 'House'),
        (SPLIT_HOUSE, 'Split House'),
        (APARTMENT, 'Apartment')
    )
    type_of_home = models.IntegerField(choices=HOME_CHOICES, blank=True, null=True)

    price = models.IntegerField()
    sq_footage = models.IntegerField(blank=True, null=True)

    beds = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(10)], blank=True, null=True)
    bathrooms = models.FloatField(validators=[MinValueValidator(1), MaxValueValidator(8)], blank=True, null=True)

    # Dog Permission
    YES = 1
    NO = 2
    MAYBE = 3
    PERMISSION_CHOICES = (
        (YES, 'yes'),
        (NO, 'no'),
        (MAYBE, 'maybe'),
    )
    dog_permission = models.IntegerField(choices=PERMISSION_CHOICES, blank=True, null=True)

    # Neighborhood 
    POINT_BREEZE = 1
    NEWBOLD = 2
    PASSYUNK_SQUARE = 3
    GRAD_HOSPITAL = 4
    HAWTHORNE = 5
    BELLA_VISTA = 6
    QUEEN_VILLAGE = 7
    UNIV_CITY = 8
    FITLER_SQUARE = 9
    RITTENHOUSE_SQUARE = 10
    WASHINGTON_SQUARE = 11
    SOCIETY_HILL = 12
    OLD_CITY = 13
    CHINATOWN = 14
    WEST_PASSYUNK = 15
    CENTRALSOUTH_PHILLY = 16
    FAIRMOUNT = 17
    GRAYS_FERRY = 18
    NEIGHBORHOOD_CHOICES = (
        (POINT_BREEZE, 'Point Breeze'),
        (NEWBOLD, 'Newbold'),
        (PASSYUNK_SQUARE, 'Passyunk Square'),
        (GRAD_HOSPITAL, 'Graduate Hospital'),
        (HAWTHORNE, 'Hawthorne'),
        (BELLA_VISTA, 'Bella Vista'),
        (QUEEN_VILLAGE, 'Queen Village'),
        (UNIV_CITY, 'University City'),
        (FITLER_SQUARE, 'Fitler Square'),
        (RITTENHOUSE_SQUARE, 'Rittenhouse Square'),
        (WASHINGTON_SQUARE, 'Washington Square'),
        (SOCIETY_HILL, 'Society Hill'),
        (OLD_CITY, 'Old City'),
        (CHINATOWN, 'Chinatown'),
        (WEST_PASSYUNK, 'West Passyunk'),
        (CENTRALSOUTH_PHILLY, 'CentralSouth Philly'),
        (FAIRMOUNT, 'Fairmount'),
        (GRAYS_FERRY, 'Grays Ferry'),
    )
    neighborhood = models.IntegerField(choices=NEIGHBORHOOD_CHOICES, blank=True, null=True)


    # = = = = = = Notes = = = = = = #
    # ============================= #

    # This includes the bedroom as-well as other rooms
    room_notes = models.CharField(max_length=1000, blank=True, null=True) # office potential/large primary bedroom/etc.

    bathroom_notes = models.CharField(max_length=1000, blank=True, null=True) # double sink/old/etc.

    kitchen_notes = models.CharField(max_length=1000, blank=True, null=True) # small or big/cabinets/stovetop/water dispensar fridge

    dog_notes = models.CharField(max_length=1000, blank=True, null=True) # park, neighborhood, house thoughts.  Windows, his stuff etc.

    parking_notes = models.CharField(max_length=1000, blank=True, null=True)

    storage_bool = models.BooleanField(blank=True, null=True)

    # Outdoor area
    outdoor_bool = models.BooleanField(blank=True, null=True)
    outdoor_name = models.CharField(max_length=100, null=True, blank=True) # patio, deck, rooftop, front porch, etc.
    outdoor_notes = models.CharField(max_length=1000, blank=True, null=True) # rooftop, backyard, balcony, etc.

    # = = = = = = Scores = = = = = = #
    # ============================== #

    # weight the below items based on importance.  Potentially come up with a model to calculate score?  
    # Would need to look into a scientific (the best) way to calculate that score

    distance_to_park_score = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(10)], blank=True, null=True)

    # - Food - #
    food_score = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(10)], blank=True, null=True)
    
    # - Stores - #
    errand_stores_score = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(10)], blank=True, null=True)
    shopping_score = models.IntegerField(blank=True, null=True)

    # - Fun - #
    nightlife_score = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(10)], blank=True, null=True)
    #sports_complex_score = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(10)], blank=True, null=True)
    #distance_to_friends_score = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(10)], blank=True, null=True)

    # = = = = = = Commutes = = = = = = #
    # ================================ #
    car_commute_work = models.CharField(max_length=100, blank=True, null=True)
    bus_commute_work = models.CharField(max_length=100, blank=True, null=True)
    walk_commute_work = models.CharField(max_length=100, blank=True, null=True)
    walk_dist_commute_work = models.CharField(max_length=100, blank=True, null=True)

    car_commute_gym = models.CharField(max_length=100, blank=True, null=True)
    bus_commute_gym = models.CharField(max_length=100, blank=True, null=True)
    walk_commute_gym = models.CharField(max_length=100, blank=True, null=True)
    walk_dist_commute_gym = models.CharField(max_length=100, blank=True, null=True)

    # When we go to save the house, if the user has a work/gym address calc it.  If not , they'll have 
    # to do it from the update button on the view house page

    # = = = = = Coordinates = = = = = #
    # =============================== #
    latitude = models.FloatField(blank=True, null=True)
    longitude = models.FloatField(blank=True, null=True)

class Profile(models.Model):

    def __str__(self):
        return self.user.username

    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)

    work_address = models.CharField(max_length=1000, blank=True, null=True)

    gym_address = models.CharField(max_length=1000, blank=True, null=True)

    #friend_addresses = models.ManyToManyField('Friend_Address', blank=True, null=True)

'''
class Friend_Address(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    address = models.CharField(max_length=400, null=True)







"At a glance" table with 3 KPIs


- - Pricing - -
a | b | c

- - Ratings - -
1 - a | b
2 - a | b
3 - a | b
4 - a | b
5 - a | b

- - Features - -
Commute ...
1 - a | b
2 - a | b
3 - a | b
4 - a | b

Neighborhood Info ...
1 - a | b
2 - a | b
3 - a | b

High Level ...
1 - a | b
2 - a | b
3 - a | b
4 - a | b
5 - a | b

High Level ...
1 - a | b
2 - a | b

- - Categories - - 
Shared Categories - a | b
Unique Categories - a | b | c

Pictures?

Map that adjusts based on location?

'''

templates/profile/add-house.html
{% load static %}

{% load crispy_forms_tags %}

<html>

    <head>

        <meta charset="utf-8"/>

        <meta name="viewport" content="width-device-width, initial-scale=1, maximum-scale=1"/>

        <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
        
        <link rel="stylesheet" type="text/css" href="https://bootswatch.com/5/solar/bootstrap.min.css">

        <title> House Hunt | Add a House </title>

    </head>

    {% include 'profile/base.html' %}

    <br>

    <br>

    <h1 class="text-center"> Add a House </h1>

    <hr>

    <div class="add_house_container bg-white shadow-md p-5">

        <div class="image_container"> <img src="{% static 'images/neighborhoods.png' %}" alt="Philly Neighborhoods"> </div>

        <br> <br>

        <div class="form_container">

            <form method="POST" autocomplete="off">

                {% csrf_token %}

                <br>

                {{ form.address|as_crispy_field}}

                <br>

                {{ form.neighborhood|as_crispy_field }}
                
                <br>

                {{ form.web_address|as_crispy_field}}

                <br>

                {{ form.price|as_crispy_field}}

                &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
                
                {{ form.beds|as_crispy_field}}

                &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

                {{ form.bathrooms|as_crispy_field}}

                &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

                {{ form.sq_footage|as_crispy_field}}


                &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

                {{ form.type_of_home|as_crispy_field}}

                &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

                {{ form.dog_permission|as_crispy_field}}

                <br>

                <input class="btn btn-outline-primary navbar-btn" type="submit" value="Add Home"/>

            </form>

        </div>
    
    </div>

</html>

templates/profile/base.html
<nav class="navbar navbar-expand-lg navbag-light bg-light justify-content-center">

    <a class="navbar-brand main-heading">

        &nbsp; House Hunt

    </a>

    <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarNavDropdown"
        aria-controls="navbarNavDropdown"
        aria-expanded="false"
        aria-label="Toggle navigation"
    >
        <span class="navbar-toggler-icon"></span>

    </button>

        <div class="collapse navbar-collapse text-center" id="navbarNavDropdown">

            <ul class="navbar-nav ml-auto">

                    &nbsp; &nbsp; &nbsp;

                    <li class="nav-item">

                        <a class="btn btn-outline-info navbar-btn" type="button" href="{% url 'user-home' %}"> Homepage </a>

                    </li>

                    &nbsp; &nbsp; &nbsp;

                    <li class="nav-item"> 

                        <a class="btn btn-outline-primary navbar-btn" type="button" href="{% url 'view-houses' %}"> View Houses </a>

                    </li>

                    &nbsp; &nbsp; &nbsp;

                    <li class="nav-item"> 

                        <a class="btn btn-outline-primary navbar-btn" type="button" href="{% url 'add-house' %}"> Add House </a>

                    </li>

                    &nbsp; &nbsp; &nbsp;

                    <li class="nav-item"> 

                        <a class="btn btn-outline-primary navbar-btn" type="button" href="{% url 'compare-houses' %}"> Compare Houses </a>

                    </li>

                    &nbsp; &nbsp; &nbsp;

                    <li class="nav-item"> 

                        <a class="btn btn-outline-danger navbar-btn" type="button" href="{% url 'test-compare' %}"> Development Page </a>

                    </li>

                    &nbsp; &nbsp; &nbsp;

                    <li class="nav-item"> 

                        <a class="btn btn-outline-success navbar-btn" type="button" href="{% url 'user-profile' %}"> Profile </a>

                    </li>

                    &nbsp; &nbsp; &nbsp;

                    <li class="nav-item"> 

                        <a class="btn btn-outline-secondary navbar-btn" type="button" href="{% url 'user-logout' %}"> Logout </a>

                    </li>

                    &nbsp; &nbsp; &nbsp;

            </ul>

        </div>

</nav>

templates/profile/compare-houses.html
{% load static %}

<html>

    <head>

        <meta charset="utf-8"/>

        <meta name="viewport" vontent="width-device-width, initial-scale=1, maximum-scale=1"/>

        <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
        
        <link rel="stylesheet" type="text/css" href="https://bootswatch.com/5/solar/bootstrap.min.css">

        <title> House Hunt | View Houses </title>

    </head>

    <h1> House Hunt | House View </h1>

<form action="{% url 'display_comparison' %}" method="get">
    <select name="pk1">
        {% for house in houses %}
            <option value="{{ house.id }}">{{ house.address }}</option>
        {% endfor %}
    </select>
    <select name="pk2">
        {% for house in houses %}
            <option value="{{ house.id }}">{{ house.address }}</option>
        {% endfor %}
    </select>
    <select name="pk3">
        <option value="">--none--</option>
        {% for house in houses %}
            <option value="{{ house.id }}">{{ house.address }}</option>
        {% endfor %}
    </select>
    <button type="submit">Compare Houses</button>
</form>

templates/profile/house-view.html
{% load static %}

<html>

    <head>

        <meta charset="utf-8"/>

        <meta name="viewport" vontent="width-device-width, initial-scale=1, maximum-scale=1"/>

        <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
        
        <link rel="stylesheet" type="text/css" href="https://bootswatch.com/5/solar/bootstrap.min.css">

        <title> House Hunt | View Houses </title>

    </head>

    {% include 'profile/base.html' %}

    <br>

    <h1> House Hunt | House View </h1>

    <body>
        <div class="compare-container-wrapper">

            <!-- Top Left : Neighborhood Map -->
            <div class="view_house_container_img"> <img style="height: 380px; width: 525px;" src="{% static 'images/neighborhoods.png' %}" alt="Philly Neighborhoods"/> </div>
            
            <!-- Top Middle : House information -->
            <div class="view_house_container_nonmap">
                <h2> {{house.address}} </h2>
                <p> <a class="btn btn-outline-info navbar-btn" type="button" href="https://{{house.web_address}}" target="_blank"> Link to the Listing </a> </p>
                <p> Neighborhood: {{house.get_neighborhood_display}}</p>
                <p> Price:  ${{house.price}}/month &nbsp; &nbsp; | &nbsp; &nbsp; Sq. Footage:  {{house.sq_footage}} ft</p>
                <p> {{house.beds}} bedrooms &nbsp; &nbsp; | &nbsp; &nbsp; {{house.bathrooms}} bathrooms</p>
                <p> Type of Home: {{house.get_type_of_home_display}}</p>
                <p> Pet Permission: {{house.get_pet_permission_display}}</p>
                <p> <a class="btn btn-outline-info navbar-btn" type="button" href="{% url 'update-house' house.id%}"> Update House Info </a> &nbsp; 
                    &nbsp; &nbsp; | &nbsp; &nbsp; &nbsp; <a class="btn btn-outline-primary navbar-btn" type="button" href="{{house.web_address}}"> Archive House </a> </p>

            </div>
            
            <!-- Top Right : Status  and Scores -->
            <div class="view_house_container_nonmap">

                <h2> Scores </h2>
                <p> Food: {{house.food_score}} &nbsp; &nbsp; &nbsp; | &nbsp; &nbsp; &nbsp; Nightlife: {{house.nightlife_score}} </p>
                <p> Shopping: {{house.shopping_score}} &nbsp; &nbsp; &nbsp; | &nbsp; &nbsp; &nbsp; Errands: {{house.errand_stores_score}}</p>
                <p> Distance to Park Score: {{house.distance_to_park_score}}</p>
                <br>
                <h2> Status</h2>
                <!-- Update the below line so that the hyperlinks ask if you're sure you want to archive and on yes, it does that and redirects you-->
                <p> <a class="btn btn-outline-info navbar-btn" type="button" href="{% url 'update-status' house.id %}"> Update Status </a> </p>
                <p> Date Available: {{house.date_available}} &nbsp; &nbsp; | &nbsp; &nbsp; Application Status: {{house.applied_status}} </p>
                <p> Next Steps: &nbsp; {{house.next_steps}} </p>
                <br>

            </div>

            <!-- Bottom Left : Google Map -->
            <div class="view_house_container_img"> <img style="height: 380px; width: 525px;" src="https://maps.googleapis.com/maps/api/staticmap?center=39.940946,-75.179623&zoom=13&size=515x390&markers=color:blue|label:H|{{house.latitude}},{{house.longitude}}&markers=color:red|label:W|{{uc.work_lat}},{{uc.work_long}}&key=AIzaSyD6TEGiGHpX80TkzkP5VIKlyPl0lWFNo7k"/> </div>

            <!-- Bottom Middle : Notes -->
            <div class="view_house_container_nonmap">

                <h2> Notes </h2>
                <p> <a class="btn btn-outline-info navbar-btn" type="button" href="{% url 'update-notes' house.id %}"> Update Notes </a> </p>
                <p> Rooms: {{house.room_notes}} </p>
                <p> Bathrooms: {{house.bathroom_notes}} </p>
                <p> Kitchen: {{house.kitchen_notes}}</p>
                <p> Dog: {{house.dog_notes}} </p>
                <p> Parking: {{house.parking_notes}}</p>
                <!-- Need to figure out how to display out-->
                <p> Storage: {{house.storage_bool}} &nbsp; &nbsp; &nbsp; | &nbsp; &nbsp; &nbsp; Outdoor Area: {{house.outdoor_bool}} </p>
                

            </div>
        
            <!-- Bottom Right : Commutes -->
            <div class="view_house_container_nonmap">

                <h2> Commutes </h2>
                <p> <a class="btn btn-outline-info navbar-btn" type="button" href="{% url 'update-commutes' house.id%}"> Calculate Commutes </a> </p>
                
                <br>

                <div class="commute-container">
                    
                    <div class="commute-section">
                        <h3> Work </h3>
                        <div class="commute-body"> 
                            <p> Bus: {{house.bus_commute_work}}</p>
                            <p> Car: {{house.car_commute_work}}</p>
                            <p> Walk (Time): {{house.walk_commute_work}}</p>
                            <p> Walk (Dist): {{house.walk_dist_commute_gym}}</p>
                        </div>
                    </div>
                    
                    <div class="commute-section">
                        <h3> Gym </h3>
                        <div class="commute-body">
                            <p> Bus: {{house.bus_commute_gym}}</p>
                            <p> Car: {{house.car_commute_gym}}</p>
                            <p> Walk (Time): {{house.walk_commute_gym}}</p>
                            <p> Walk (Dist): {{house.walk_dist_commute_gym}}</p>
                        </div>
                    </div>

                </div>
                
            </div>
    </body>

</html>

templates/profile/old-house-view.html
{% load static %}

<html>

    <head>

        <meta charset="utf-8"/>

        <meta name="viewport" vontent="width-device-width, initial-scale=1, maximum-scale=1"/>

        <link rel="stylesheet" type="text/css" href="https://bootswatch.com/5/solar/bootstrap.min.css">
        
        <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">

        <title> House Hunt | View Houses </title>

    </head>

    {% include 'profile/base.html' %}

    <br>

    <h1> House Hunt | View a House </h1>

    <br> <br>

    <div class="container bg-white shadow-md p-5 form-layout">

        <h2> {{house.address}} 
        
        <br>

        <a class="btn btn-info navbar-btn" type="button" href="{{house.web_address}}"> Link to the Listing </a> </h2>    

        <br>

        <p> Neighborhood: {{house.get_neighborhood_display}}</p>

        <p> Price:  ${{house.price}}/month &nbsp; &nbsp; | &nbsp; &nbsp; Sq. Footage:  {{house.sq_footage}} ft</p>

        <p> {{house.beds}} bedrooms &nbsp; &nbsp; | &nbsp; &nbsp; {{house.bathrooms}} bathrooms</p>

        <p> Type of Home: {{house.get_type_of_home_display}}</p>

        <p> Pet Permission: {{house.get_pet_permission_display}}</p>
        
        <br>

        <h3> Scores </h3>

        <p> Food: {{house.food_score}} &nbsp; &nbsp; | &nbsp; &nbsp; Shopping: {{house.shopping_score}}
            &nbsp; &nbsp; | &nbsp; Errands: {{house.errand_sotres_score}} &nbsp; &nbsp; | &nbsp; Nightlife: {{house.nightlife_score}}
        </p>

        <p> Small Park Score: {{house.small_park_distance_score}} &nbsp; &nbsp; | &nbsp; &nbsp; Big Park Score: {{house.big_park_distance_score}} </p>

        <br>

        <h3> Notes </h3>

        <p> Dog: {{house.dog_notes}} </p>

        <p> Rooms: {{house.room_notes}} </p>

        <p> Bathrooms: {{house.bathroom_notes}} </p>

        <p> Kitchen: {{house.kitchen_notes}} </p>

        <br> <br>

        <a class="btn btn-info" type="button" href="{% url 'update-house' house.id %}"> Update This House </a>

        <br> <br>

        <a class="btn btn-info" type="button" href="{% url 'view-houses' %}"> Go back to the List of Houses </a>

    </div>

</html>

templates/profile/testcomparison.html
{% load static %}

<html>

    <head>

        <meta charset="utf-8"/>

        <meta name="viewport" vontent="width-device-width, initial-scale=1, maximum-scale=1"/>

        <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
        
        <link rel="stylesheet" type="text/css" href="https://bootswatch.com/5/solar/bootstrap.min.css">

        <title> House Hunt | View Houses </title>

    </head>

    {% include 'profile/base.html' %}

    <br>

    <h1> House Hunt | Comparing Houses Display </h1>

    <!-- Vision
    
        Container across the top for the google map

        3 Containers below containing the mini containers for each of our 3 houses to compare
        If we only have 2 I want it to only show 2 containers

    -->

    <body>
        
        <!-- Comparison Container that will house our 2-3 houses -->
        <div class="levelA_container">
            Main Container
            <!-- House Container 1 -->
            <div class="levelB_container">
                House 1
                <!-- Attribute Container 1 -->
                <div class="levelC_container">
                    Level C - House 1 - Container 1
                </div>
                    <!-- Attribute Container n -->
                <div class="levelC_container">
                    Level C - House 1 - Container 2
                </div>
            </div>
                
            <!-- House Container n -->
            <div class="levelB_container">
                House 2
                <!-- Attribute Container 1 -->
                <div class="levelC_container">
                    Level C - House 2 - Container 1
                </div>
                    <!-- Attribute Container n -->
                <div class="levelC_container">
                    Level C - House 2 - Container 2
                </div>
            </div>
        
        </div>
    </body>

</html>

templates/profile/update-notes.html
{% load static %}

{% load crispy_forms_tags %}

<html>

    <head>

        <meta charset="utf-8"/>

        <meta name="viewport" content="width-device-width, initial-scale=1, maximum-scale=1"/>

        <link rel="stylesheet" type="text/css" href="https://bootswatch.com/5/solar/bootstrap.min.css">
        
        <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">

        <title> House Hunt | Update Notes </title>

    </head>

    {% include 'profile/base.html' %}

    <br>

    <div class="container bg-white shadow-md p-5 form-layout">

        <h1> Update Status </h1>

        <hr>

        <form method="POST" autocomplete="off">

            {% csrf_token %}

            {{ form.room_notes|as_crispy_field }}

            <br>

            {{ form.bathroom_notes|as_crispy_field }}

            <br>

            {{ form.kitchen_notes|as_crispy_field }}

            <br>

            {{ form.dog_notes|as_crispy_field }}

            <br>

            {{ form.parking_notes|as_crispy_field }}

            <br>

            {{ form.storage_bool|as_crispy_field }}

            <br>

            {{ form.outdoor_bool|as_crispy_field }}

            <br>

            {{ form.outdoor_name|as_crispy_field }}

            <br>

            {{ form.outdoor_notes|as_crispy_field }}

            <br>

            <input class="btn btn-primary navbar-btn" type="submit" value="Submit Changes" />

            <br>

        </form>

        <a class="btn btn-outline-primary" type="button" href="{% url 'read-house' form.instance.pk %}"> Go back to the house </a>

    </div>

templates/profile/view-houses.html
{% load static %}

<html>

    <head>

        <meta charset="utf-8"/>

        <meta name="viewport" vontent="width-device-width, initial-scale=1, maximum-scale=1"/>

        <link rel="stylesheet" type="text/css" href="https://bootswatch.com/5/solar/bootstrap.min.css">
        
        <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">

        <title> House Hunt | View Houses </title>

    </head>

    {% include 'profile/base.html' %}

    <br>

    <h1> House Hunt | View Houses </h1>

    <div class="container bg-white shadow-md p-5 form-layout" style="width: 800px; ">
        
        <h2 style="display: inline-block; text-align: justify;"> List of Houses <span class="right_button"> <a class="btn btn-outline-info navbar-btn" type="button" href="{% url 'update-lat-long' %}"> Update Latitude and Longitude for All Houses </a> </span> </h2>

        <ul class="house-list">
            {% for house in houses %}
                <li class="house-item"></li>
                    <div class="house-address"> Address: &nbsp; {{house.address}} </div>
                    <div class="house-neighborhood"> Neighborhood: &nbsp; {{house.get_neighborhood_display}} </div>
                    <div class="house-price"> Price: &nbsp; ${{house.price}}/month </div>
                    <div class="house-sqft"> Sq. Footage: &nbsp; {{house.sq_footage}}ft </div>
                    <div class="house-link"> <a href="{% url 'read-house' house.id %}"> View House </a></div>
            {% endfor %}
        </ul>

    </div>

    <br>